export enum actionTypes {
    FETCH_ALL_BOOKS = "FETCH_ALL_BOOKS",
    CREATE_BOOK = "CREATE_BOOK",
    UPDATE_BOOK = "UPDATE_BOOK",
    DELETE_BOOK = "DELETE_BOOK",
    BOOK_ERROR = "BOOK_ERROR"
};



